### ISSUE TITLE
Restful API with 2 Processes to fetching Trades and L2 Depth data will cause side effect

### ISSUE THREAD

**Issue by rendonghai** [Aurora-Team/BitcoinExchangeFH#107]
Hi,

I thought you might not be that familiar with Process and thread. 
Creating threads in on a process, these threads will share objects in the mem.
However, creating multiple processes from the father process, these child process will never share memories, unless there is message queue or socket communication or any other methods. 

Just keep use threading in an Exchange GW class in function with name 'start'.

**Comment by gavincyi** [comment]
Yes duplicated with #117. Thanks.
