### ISSUE TITLE
Add some changes

### ISSUE THREAD

**Issue by sanchoflat** [Aurora-Team/BitcoinExchangeFH#114]
Hi, I have some problems with code change. I want to disable orderBook loading, only trades. But i cant build it. I found some **bitcoinexchangefh.exe** file in Python scripts folder. How can I change it with my code changes? Thx.

**Comment by edandavi** [comment]
Hi,
can you please link the changes you're mentioning, 
did you try running "python setup.py install" after you made the code changes?
I'm also interested in this kind of functionality where you can set if the order book is to be recorded or not.
maybe we can simultaneously deal with #37 at the same time by adding an l2_depth variable in the subscription .ini?

**Comment by gavincyi** [comment]
It's related to #108 and requires the change in setup.py. Will resolve soon.
