### ISSUE TITLE
Binance MySQL,  SQL error: (1062, "Duplicate entry '748' for key 'PRIMARY'")

### ISSUE THREAD

**Issue by pelyxp** [Aurora-Team/BitcoinExchangeFH#117]
when running Binance , there is always an 
SQL error: (1062, "Duplicate entry '748' for key 'PRIMARY'")

I'm a DBA and I have no experience with python, just read little documents, 
so if following issue analysis maybe incorrect .

I have done some trace,
BTCUSDT 747
print from following code in gateway.py
```
    def get_instmt_snapshot_id(self, instmt):
        with self.lock:
            self.exch_snapshot_id += 1
            print(instmt.instmt_name, self.exch_snapshot_id)
```
ordrbook BTCUSDT 747  ----> print from gateway.py  insert_order_book
trade BTCUSDT 746    ----> print from gateway.py insert_trade

```
BTCUSDT 747
ordrbook BTCUSDT 747
BTCUSDT 748
ordrbook BTCUSDT 748
BTCUSDT 746
trade BTCUSDT 746

BTCUSDT 749
ordrbook BTCUSDT 749
BTCUSDT 747
trade BTCUSDT 747

BTCUSDT 750
ordrbook BTCUSDT 750
BTCUSDT 748
trade BTCUSDT 748


BTCUSDT 749
trade BTCUSDT 749

BTCUSDT 750
trade BTCUSDT 750

```

from above trace message
we can find that the exch_snapshot_id for trade worker is not synced with exch_snapshot_id for orderbook worker. 
eg,  orderbook worker get exch_snapshot_id 747 first  , and insert order_book to snapshot tables with id 747
and then , after some time , trade worker get exch_snapshot_id 747,  when trade worker insert into same snapshot table with id 747, there will be a duplicate pk error. 

to reslove this,  ether add some Synchronization mechanism to make exch_snapshot_id synced in both worker. 
or , insert trade and orderbook into different table. 

Here I also have another question , why put the trade data and order book data into same table?

**Comment by pelyxp** [comment]
#107 
maybe related with issue 107

**Comment by pelyxp** [comment]
#107

**Comment by gavincyi** [comment]
Yes I spotted that a few exchanges use `multiprocessing.Process` to spawn the child processes, rather than thread. The lock does not work on that way. It will be resolved soon.

Thanks for reporting the issue.

> Here I also have another question , why put the trade data and order book data into same table?

Well it's due to the design to make analysis easy. Open to hear how the users use this project and the expected changes to facilitate your work.

**Comment by ddeath** [comment]
In my case, I have a problem with Bitfinex exchange. But I think it does not have a problem with locks. It shows the same error if there are some records in the table. In other words, if you start with empty tables, there is no problem.

@pelyxp does the problem occurs even when you start with empty tables?

**Comment by pelyxp** [comment]
@ddeath the problem occurs whether start with an empty table or not
following is a log for start from empty tables.

`XRPETH 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
ordrbook XRPETH 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
ETHUSDT 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ordrbook ETHUSDT 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
ETHUSDT 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ordrbook ETHUSDT 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
XRPETH 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
ordrbook XRPETH 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
ETHUSDT 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
trade ETHUSDT 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

2018-03-02 00:17:00,322 - INFO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
[MysqlClient]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
SQL error: (1062, "Duplicate entry '1' for key 'PRIMARY'")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ETHUSDT 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
trade ETHUSDT 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
2018-03-02 00:17:00,333 - INFO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
[MysqlClient]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
SQL error: (1062, "Duplicate entry '2' for key 'PRIMARY'")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ETHUSDT 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ordrbook ETHUSDT 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
ETHUSDT 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
trade ETHUSDT 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
2018-03-02 00:17:02,276 - INFO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
[MysqlClient]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
SQL error: (1062, "Duplicate entry '3' for key 'PRIMARY'")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ETHUSDT 4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
trade ETHUSDT 4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
ETHUSDT 5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
trade ETHUSDT 5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
ETHUSDT 6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
trade ETHUSDT 6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
ETHUSDT 7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
trade ETHUSDT 7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
ETHUSDT 8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
trade ETHUSDT 8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
ETHUSDT 9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
trade ETHUSDT 9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
ETHUSDT 10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
trade ETHUSDT 10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ETHUSDT 11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
trade ETHUSDT 11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ETHUSDT 12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
trade ETHUSDT 12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ETHUSDT 13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
trade ETHUSDT 13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ETHUSDT 14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
trade ETHUSDT 14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ETHUSDT 15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
trade ETHUSDT 15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ETHUSDT 16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
trade ETHUSDT 16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
XRPETH 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
ordrbook XRPETH 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
ETHUSDT 4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ordrbook ETHUSDT 4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
2018-03-02 00:17:04,175 - INFO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
[MysqlClient]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
SQL error: (1062, "Duplicate entry '4' for key 'PRIMARY'")     `
