### ISSUE TITLE
Handler for  "too many requests", "unsubscribed", "close"

### ISSUE THREAD

**Issue by jpspfaria** [Aurora-Team/BitcoinExchangeFH#36]
Hi @gavincyi , how are you doing?

Is there a way to handle the APIs that responds with "too many requests", "unsubscribed" and "close".

Could you put the parameter "sleep", at the subscriptions.ini file?
It would be nice to control the waiting time for the next request

It would be great to have multiple sources for the same instrument as a redundancy mechanism
(Websocket, HTTP, FIX)

This are the status messages that i got in my log:

[ExchGwOkCoinWs] - Socket <ExchGwOkCoin> error: Connection is already closed.
[ExchGwOkCoinWs] - Socket <ExchGwOkCoin> is closed.
[ExchGwOkCoinWs] - Socket <ExchGwOkCoin> is going to reconnect...

[ExchGwOkCoin] - Instrument spotusd_btc is unsubscribed in channel OkCoin
[ExchGwOkCoin] - Instrument futureusd_btc_quarter is unsubscribed in channel OkCoin

[ExchGwQuoine] - Error in trades: HTTP Error 429: Too Many Requests
[ExchGwQuoine] - Error in order book: HTTP Error 429: Too Many Requests

**Comment by gavincyi** [comment]
The log message from OkCoin is due to disconnection from the socket. To be honest I have no idea why OkCoin kept disconnecting their client (or probably due to a unstable connection to OkCoin server). I faced the similar issue in my server. Currently it successfully reconnects and subscribes the instruments so I put it aside.

For the Quoine issue, may I know again your version using? #22 should have resolved it and I did not see such error again in my server.

**Comment by jpspfaria** [comment]
Hey @gavincyi , you were right!
I updated just the repository, the python package wasn't uptodate.

I got some problems that my socketIO_client was newer than the requirements because of the version of python running on CONDA.

On the first Run everything went OK (Smooth!), but when i try to run it again on the same database schema, i am getting a bunch of errors related to duplicate primary key.

How can i solve this if i need to get the software back online for the second time in the same day?

LOG
SQL error: (1062, "Duplicate entry '27' for key 'PRIMARY'")

Another question:
The date used on for creating the table name is related to my server date, or is it using the exchange local date?

exch_bitmex_xbtusd_snapshot_**20170422**

If the process is running on the server, and the date flips after 00:00, does your software creates a new table automatically with the new date or i have to restart the process after 00:00 to create the new tables?

Thanks for the help! This new version looks much better :-) Nice improvements

**Comment by jpspfaria** [comment]
Thanks for the fast reply.
Everything is working just fine on the new version!

Great work! Thanks a lot for your contribution.
On the next bitcoin meetup here in São Paulo/Brazil i will show your framework and i let you know the comments!

**Comment by jpspfaria** [comment]
Hi @gavincyi, me again!

I was looking at the table structures, it would be nice to have  a column in every table of the system named create_date_time using the server local time.

Good for monitoring and working with the data!

Hey would be great to talk to you on skype, please add jpspfaria

Tks

**Comment by gavincyi** [comment]
For a few changes in the last month, the application does not support recovery of market data now. So the application assumes the application starts without previous records. The error of duplicated keys means there are previous records in the table. What you need is to clear/delete the table and run it again.

May I know what is the definition of the create_date_time? Did you mean it is the record creation time in local server time?

Thanks for your comment again. :)

**Comment by jpspfaria** [comment]
Hi @gavincyi , create_date_time is exactly that! Local server time at the record creation.

Related to the duplicate data, the best choice that i can see is to let MySQL manage and validate the **id**(With auto increment), **order_date_time**, **trade_date_time** and **create_date_time** fields as primary keys, preventing duplicate records on the table

**Comment by gavincyi** [comment]
On the local timezone, I think a timezone input variable can be provided during startup and it is a good idea to enhance it.

For the create_date_time, it looks to me it is duplicated with the latest of order_date_time and trade_date_time. What is the rationale behind?

Auto increment is convenient to ensure unique key but I was aware of using it during writing this project as it may increase the latency of writing records. My understanding is auto increment makes the table locked during insertion. Please correct me if I am wrong.

Thanks for your advice again.
