### ISSUE TITLE
need help with project

### ISSUE THREAD

**Issue by silverbuyer** [Aurora-Team/BitcoinExchangeFH#38]
looking to have quote screen for users pulling from updates to mysql database..can you help? any skype?

the project is written in php so far
please email me at showbox654265@gmail.com

**Comment by silverbuyer** [comment]
by the way this has nothing to do with bitcoin it is for silver trading

**Comment by gavincyi** [comment]
Is it an open source project?

**Comment by silverbuyer** [comment]
no i am not a developper


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Gavin Chan <notifications@github.com> Date: 2017-05-31  6:16 AM  (GMT-05:00) To: Aurora-Team/BitcoinExchangeFH <BitcoinExchangeFH@noreply.github.com> Cc: silverbuyer <showbox654265@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Aurora-Team/BitcoinExchangeFH] need help with project (#38) 
Is it an open source project?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Aurora-Team/BitcoinExchangeFH","title":"Aurora-Team/BitcoinExchangeFH","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Aurora-Team/BitcoinExchangeFH"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gavincyi in #38: Is it an open source project?"}],"action":{"name":"View Issue","url":"https://github.com/Aurora-Team/BitcoinExchangeFH/issues/38#issuecomment-305148365"}}}

**Comment by gavincyi** [comment]
Sorry I work on open source project currently only. Thanks for your approach anyway. :)
