### ISSUE TITLE
Issues inserting all Bittrex Tickers into KDB+ Database

### ISSUE THREAD

**Issue by cryptoGitWatcher** [Aurora-Team/BitcoinExchangeFH#56]
I'm trying to log all ticker information from bittrex into a KDB+ database using the following subscriptions.ini file. This is almost a fulll list of tickers for Bittrex:

```
[Bittrex-BTC1ST-Restful]
exchange = Bittrex
instmt_name = BTC1ST
instmt_code = BTC-1ST
enabled = 1
[Bittrex-BTCAGRS-Restful]
exchange = Bittrex
instmt_name = BTCAGRS
instmt_code = BTC-AGRS
enabled = 1
[Bittrex-BTCAMP-Restful]
exchange = Bittrex
instmt_name = BTCAMP
instmt_code = BTC-AMP
enabled = 1
[Bittrex-BTCARDR-Restful]
exchange = Bittrex
instmt_name = BTCARDR
instmt_code = BTC-ARDR
enabled = 1
[Bittrex-BTCBAY-Restful]
exchange = Bittrex
instmt_name = BTCBAY
instmt_code = BTC-BAY
enabled = 1
[Bittrex-BTCBCY-Restful]
exchange = Bittrex
instmt_name = BTCBCY
instmt_code = BTC-BCY
enabled = 1
[Bittrex-BTCBYC-Restful]
exchange = Bittrex
instmt_name = BTCBYC
instmt_code = BTC-BYC
enabled = 1
[Bittrex-BTCCLOAK-Restful]
exchange = Bittrex
instmt_name = BTCCLOAK
instmt_code = BTC-CLOAK
enabled = 1
[Bittrex-BTCCLUB-Restful]
exchange = Bittrex
instmt_name = BTCCLUB
instmt_code = BTC-CLUB
enabled = 1
[Bittrex-BTCCPC-Restful]
exchange = Bittrex
instmt_name = BTCCPC
instmt_code = BTC-CPC
enabled = 1
[Bittrex-BTCCRB-Restful]
exchange = Bittrex
instmt_name = BTCCRB
instmt_code = BTC-CRB
enabled = 1
[Bittrex-BTCDASH-Restful]
exchange = Bittrex
instmt_name = BTCDASH
instmt_code = BTC-DASH
enabled = 1
[Bittrex-BTCDGD-Restful]
exchange = Bittrex
instmt_name = BTCDGD
instmt_code = BTC-DGD
enabled = 1
[Bittrex-BTCDYN-Restful]
exchange = Bittrex
instmt_name = BTCDYN
instmt_code = BTC-DYN
enabled = 1
[Bittrex-BTCEDG-Restful]
exchange = Bittrex
instmt_name = BTCEDG
instmt_code = BTC-EDG
enabled = 1
[Bittrex-BTCETH-Restful]
exchange = Bittrex
instmt_name = BTCETH
instmt_code = BTC-ETH
enabled = 1
[Bittrex-BTCFCT-Restful]
exchange = Bittrex
instmt_name = BTCFCT
instmt_code = BTC-FCT
enabled = 1
[Bittrex-BTCFTC-Restful]
exchange = Bittrex
instmt_name = BTCFTC
instmt_code = BTC-FTC
enabled = 1
[Bittrex-BTCGEO-Restful]
exchange = Bittrex
instmt_name = BTCGEO
instmt_code = BTC-GEO
enabled = 1
[Bittrex-BTCGNO-Restful]
exchange = Bittrex
instmt_name = BTCGNO
instmt_code = BTC-GNO
enabled = 1
[Bittrex-BTCGNT-Restful]
exchange = Bittrex
instmt_name = BTCGNT
instmt_code = BTC-GNT
enabled = 1
[Bittrex-BTCGRC-Restful]
exchange = Bittrex
instmt_name = BTCGRC
instmt_code = BTC-GRC
enabled = 1
[Bittrex-BTCHKG-Restful]
exchange = Bittrex
instmt_name = BTCHKG
instmt_code = BTC-HKG
enabled = 1
[Bittrex-BTCLBC-Restful]
exchange = Bittrex
instmt_name = BTCLBC
instmt_code = BTC-LBC
enabled = 1
[Bittrex-BTCLTC-Restful]
exchange = Bittrex
instmt_name = BTCLTC
instmt_code = BTC-LTC
enabled = 1
[Bittrex-BTCMEME-Restful]
exchange = Bittrex
instmt_name = BTCMEME
instmt_code = BTC-MEME
enabled = 1
[Bittrex-BTCMYST-Restful]
exchange = Bittrex
instmt_name = BTCMYST
instmt_code = BTC-MYST
enabled = 1
[Bittrex-BTCNAUT-Restful]
exchange = Bittrex
instmt_name = BTCNAUT
instmt_code = BTC-NAUT
enabled = 1
[Bittrex-BTCNAV-Restful]
exchange = Bittrex
instmt_name = BTCNAV
instmt_code = BTC-NAV
enabled = 1
[Bittrex-BTCNLG-Restful]
exchange = Bittrex
instmt_name = BTCNLG
instmt_code = BTC-NLG
enabled = 1
[Bittrex-BTCNXC-Restful]
exchange = Bittrex
instmt_name = BTCNXC
instmt_code = BTC-NXC
enabled = 1
[Bittrex-BTCNXS-Restful]
exchange = Bittrex
instmt_name = BTCNXS
instmt_code = BTC-NXS
enabled = 1
[Bittrex-BTCNXT-Restful]
exchange = Bittrex
instmt_name = BTCNXT
instmt_code = BTC-NXT
enabled = 1
[Bittrex-BTCPKB-Restful]
exchange = Bittrex
instmt_name = BTCPKB
instmt_code = BTC-PKB
enabled = 1
[Bittrex-BTCPPC-Restful]
exchange = Bittrex
instmt_name = BTCPPC
instmt_code = BTC-PPC
enabled = 1
[Bittrex-BTCPTC-Restful]
exchange = Bittrex
instmt_name = BTCPTC
instmt_code = BTC-PTC
enabled = 1
[Bittrex-BTCQRL-Restful]
exchange = Bittrex
instmt_name = BTCQRL
instmt_code = BTC-QRL
enabled = 1
[Bittrex-BTCRADS-Restful]
exchange = Bittrex
instmt_name = BTCRADS
instmt_code = BTC-RADS
enabled = 1
[Bittrex-BTCSC-Restful]
exchange = Bittrex
instmt_name = BTCSC
instmt_code = BTC-SC
enabled = 1
[Bittrex-BTCSIB-Restful]
exchange = Bittrex
instmt_name = BTCSIB
instmt_code = BTC-SIB
enabled = 1
[Bittrex-BTCSJCX-Restful]
exchange = Bittrex
instmt_name = BTCSJCX
instmt_code = BTC-SJCX
enabled = 1
[Bittrex-BTCSNRG-Restful]
exchange = Bittrex
instmt_name = BTCSNRG
instmt_code = BTC-SNRG
enabled = 1
[Bittrex-BTCSWIFT-Restful]
exchange = Bittrex
instmt_name = BTCSWIFT
instmt_code = BTC-SWIFT
enabled = 1
[Bittrex-BTCTX-Restful]
exchange = Bittrex
instmt_name = BTCTX
instmt_code = BTC-TX
enabled = 1
[Bittrex-BTCVIA-Restful]
exchange = Bittrex
instmt_name = BTCVIA
instmt_code = BTC-VIA
enabled = 1
[Bittrex-BTCVOX-Restful]
exchange = Bittrex
instmt_name = BTCVOX
instmt_code = BTC-VOX
enabled = 1
[Bittrex-BTCWINGS-Restful]
exchange = Bittrex
instmt_name = BTCWINGS
instmt_code = BTC-WINGS
enabled = 1
[Bittrex-BTCXEM-Restful]
exchange = Bittrex
instmt_name = BTCXEM
instmt_code = BTC-XEM
enabled = 1
[Bittrex-BTCXLM-Restful]
exchange = Bittrex
instmt_name = BTCXLM
instmt_code = BTC-XLM
enabled = 1
[Bittrex-BTCXMR-Restful]
exchange = Bittrex
instmt_name = BTCXMR
instmt_code = BTC-XMR
enabled = 1
[Bittrex-BTCXRP-Restful]
exchange = Bittrex
instmt_name = BTCXRP
instmt_code = BTC-XRP
enabled = 1
[Bittrex-BTCXVC-Restful]
exchange = Bittrex
instmt_name = BTCXVC
instmt_code = BTC-XVC
enabled = 1
[Bittrex-BTCXWC-Restful]
exchange = Bittrex
instmt_name = BTCXWC
instmt_code = BTC-XWC
enabled = 1
[Bittrex-BTCZEN-Restful]
exchange = Bittrex
instmt_name = BTCZEN
instmt_code = BTC-ZEN
enabled = 1
[Bittrex-ETHCRB-Restful]
exchange = Bittrex
instmt_name = ETHCRB
instmt_code = ETH-CRB
enabled = 1
[Bittrex-ETHGNO-Restful]
exchange = Bittrex
instmt_name = ETHGNO
instmt_code = ETH-GNO
enabled = 1
[Bittrex-ETHGUP-Restful]
exchange = Bittrex
instmt_name = ETHGUP
instmt_code = ETH-GUP
enabled = 1
[Bittrex-ETHQRL-Restful]
exchange = Bittrex
instmt_name = ETHQRL
instmt_code = ETH-QRL
enabled = 1
[Bittrex-ETHRLC-Restful]
exchange = Bittrex
instmt_name = ETHRLC
instmt_code = ETH-RLC
enabled = 1
[Bittrex-ETHTRST-Restful]
exchange = Bittrex
instmt_name = ETHTRST
instmt_code = ETH-TRST
enabled = 1
```

The follow error is generated after starting bitcoinexchangeFH:

>  Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/home/obnauticus/.local/lib/python3.5/site-packages/befh/kdbplus_client.py", line 217, in insert
>     self.conn.sync(command)
>   File "/home/obnauticus/.local/lib/python3.5/site-packages/qpython/qconnection.py", line 303, in sync
>     response = self.receive(data_only = False, **options)
>   File "/home/obnauticus/.local/lib/python3.5/site-packages/qpython/qconnection.py", line 380, in receive
>     result = self._reader.read(**self._options.union_dict(**options))
>   File "/home/obnauticus/.local/lib/python3.5/site-packages/qpython/qreader.py", line 139, in read
>     message.data = self.read_data(message.size, message.is_compressed, **options)
>   File "/home/obnauticus/.local/lib/python3.5/site-packages/qpython/qreader.py", line 216, in read_data
>     return raw_data if self._options.raw else self._read_object()
>   File "/home/obnauticus/.local/lib/python3.5/site-packages/qpython/qreader.py", line 225, in _read_object
>     return reader(self, qtype)
>   File "/home/obnauticus/.local/lib/python3.5/site-packages/qpython/qreader.py", line 240, in _read_error
>     raise QException(self._read_symbol())
> qpython.qtype.QException: b'insert'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/obnauticus/.local/lib/python3.5/site-packages/befh/exch_bittrex.py", line 236, in get_trades_worker
>     self.insert_trade(instmt, trade)
>   File "/home/obnauticus/.local/lib/python3.5/site-packages/befh/exchange.py", line 179, in insert_trade
>     is_commit=True)
>   File "/home/obnauticus/.local/lib/python3.5/site-packages/befh/kdbplus_client.py", line 219, in insert
>     raise Exception("Error in running insert statement (%s).\n%s" % (command, e))
> Exception: Error in running insert statement (`exch_bittrex_btc1st_snapshot_20170622 insert (1296; 0.00068; 7.08377613; 0.0006782; 0.000678; 0.00067116; 0.00067; 0.00066199; 0.00068; 0.00068885; 0.00068886; 0.00068887; 0.0006931; 234.68564114; 61.47389469; 12.48536861; 25.52632037; 16.99421441; 209.68084468; 130.88266889; 57.17452034; 8.63; 19.22753368; 2017.06.22D14:11:39.304126000; 2017.06.22D14:11:39.544221000; 2)).
> b'insert'
> 
> 2017-06-22 15:11:41,584 - ERROR
> [ExchGwBittrex]
> Error in order book: Error in running insert statement (`exch_bittrex_btcgno_snapshot_20170622 insert (1308; 0.084; 0.04219615; 0.08219567; 0.08219566; 0.08219564; 0.08219561; 0.08219556; 0.08399999; 0.084; 0.08440694; 0.08440818; 0.08555794; 7.599; 5.97443015; 26.759; 0.43233853; 0.28534343; 26.82432278; 7.0; 2.46357776; 0.19752483; 7.459; 2017.06.22D14:11:41.581279000; 2017.06.22D14:09:31.360276000; 1)).
> b'insert'
> 
> 
> 2017-06-22 15:11:43,758 - ERROR
> [ExchGwBittrex]
> Error in order book: Error in running insert statement (`exch_bittrex_btcfct_snapshot_20170622 insert (1321; 0.01168231; 0.76617289; 0.011521; 0.01152084; 0.01152018; 0.01152017; 0.01152005; 0.01168133; 0.0116815; 0.0116823; 0.01168231; 0.01168232; 0.07981868; 0.07981868; 263.3046; 590.16; 8.54815189; 0.08990821; 0.08972119; 0.090133; 1.53334305; 25.4497504; 2017.06.22D14:11:43.740125000; 2017.06.22D14:10:26.297787000; 1)).
> b'insert'

I'm not exactly sure why, but new data doesn't seem to be streaming into the KDB+. Also, not all tickers in subscriptions.ini are being updated in resources.ini. Only about half are being created. Here's a screenshot of the tables which are created when I run BitcoinExchangeFH:

[http://i.imgur.com/ZFZSM5z.png](http://i.imgur.com/ZFZSM5z.png)

Here's a full output log:

[http://sprunge.us/YDEg](http://sprunge.us/YDEg)

**Comment by gavincyi** [comment]
I am looking into the issue and will get you back soon.

One more question:
Can you run the application solely with subscription of bittrex/btcgno? Does the issue only happen when it is subscribed with other instruments?

**Comment by cryptoGitWatcher** [comment]
Using the following subscriptions_test.ini file:

```
[Bittrex-BTCGNO-Restful]
exchange = Bittrex
instmt_name = BTCGNO
instmt_code = BTC-GNO
enabled = 1
```

I get the following output:

```
2017-06-23 07:38:40,929 - INFO
[KdbPlusClient]
Kdb+ database client is connecting to localhost:5000


2017-06-23 07:38:40,930 - INFO
[KdbPlusClient]
Connection to localhost:5000 is successful.


2017-06-23 07:38:40,931 - INFO
[KdbPlusClient]
Table exchanges_snapshot is going to be created.


2017-06-23 07:38:40,932 - INFO
[[main]]
Subscription file = ./subscriptions_test.ini


2017-06-23 07:38:40,932 - INFO
[[main]]
Exchange/Instrument/InstrumentCode:
Bittrex/BTCGNO/BTC-GNO



2017-06-23 07:38:40,932 - INFO
[[main]]
Starting instrument Bittrex-BTCGNO...


2017-06-23 07:38:40,933 - INFO
[KdbPlusClient]
Table exch_bittrex_btcgno_snapshot_20170623 is going to be created.
```

Startup command:

`$ python3.5 /home/obnauticus/.local/lib/python3.5/site-packages/befh/bitcoinexchangefh.py -kdb -kdbdest "localhost:5000" -instmts ./subscriptions_test.ini -output LOG3.TXT`


I left the old subscriptions.ini (from original issue above with all Bittrex symbols) and over time it did seem to populate the KDB+ database; however this took a very long time and a lot of the information was incomplete--for example, in the exchange_summary table there was 0 trade volume for some symbols).

This issue may only be happening for large numbers of symbols being collected simultaneously from Bittrex?

**Comment by gavincyi** [comment]
Yes I suppose so. As the api calls among all instruments are synchronized calls, so the queuing calls are blocked from the return of the requesting call.

I believe the issue will be improved after the enhancement of #31 . In short term, I suggest you to separate the instruments into different processes but update the data on the same kdb database.

**Comment by gavincyi** [comment]
If you do not object I will close the issue soon.
