### ISSUE TITLE
ZeroMQ doesn't allow instmt records

### ISSUE THREAD

**Issue by zvictor** [Aurora-Team/BitcoinExchangeFH#58]
According to [exchange.py:61](https://github.com/Aurora-Team/BitcoinExchangeFH/blob/master/befh/exchange.py#L61), ZeroMQ is not allowed to handle `instmt` records, resulting only in exchange snapshots. Is there any reason for that?

**Comment by gavincyi** [comment]
The method is_allowed_instmt_record is called during checking whether to create a record of `exch_<exchange name>_<instrument name>_snapshot`. 

Actually this record is duplicated with the record of `exchanges_snapshot`. So during using ZeroMQ feed, it ensures the tick is sent out once.
