### ISSUE TITLE
websocket vs. websocket-client

### ISSUE THREAD

**Issue by backender** [Aurora-Team/BitcoinExchangeFH#59]
I just experienced an error with the combination of the libraries `websocket` and `websocket-client`: **AttributeError: 'module' object has no attribute 'WebSocketApp'**

It appears that `websocket` overrides the what is actually needed from `websocket-client`. I could resolve the issue with: `pip uninstall websocket; pip uninstall websocket-client; pip install websocket-client`. 

Therefore I suggest to remove `websocket` from requirements.

**Comment by gavincyi** [comment]
Agree. Will remove the redundancy in the next release.
