### ISSUE TITLE
Data from multiple market pairs from an exchange

### ISSUE THREAD

**Issue by tuxitor** [Aurora-Team/BitcoinExchangeFH#61]
Is it available, or is it planned support for multiple pairs from each exchange?

**Comment by gavincyi** [comment]
It is now supported. If you refer to [subscriptions.ini](https://github.com/Aurora-Team/BitcoinExchangeFH/blob/master/subscriptions.ini), you can find the following repeating blocks on the same exchange.

```
[BitMEX-XBTUSD-WS]
exchange = BitMEX
instmt_name = XBTUSD
instmt_code = XBTUSD
enabled = 1

[BitMEX-XBTZ16-WS]
exchange = BitMEX
instmt_name = XBTM17
instmt_code = XBTM17
enabled = 1
```

**Comment by tuxitor** [comment]
Thanks a lot! That answers my question :)
