### ISSUE TITLE
BitcoinExchangeFH and ZeroMQ connection issues

### ISSUE THREAD

**Issue by tuxitor** [Aurora-Team/BitcoinExchangeFH#63]
Compiling and installation of both BitcoinExchangeFH and ZeroGQ is a smith process. However I have issues with connection to ZeroMQ. Linking of the Python binding seems to work.
From the README.md it looks like ZeroMQ should be running as a free standing server
```
(bitcoinexchangefh -zmq -zmqdest "tcp://localhost:6001" -instmts subscription.ini)
```
With the above options I got this stack backtrace:
```
Zmq client is connecting to tcp://localhost:6001
Traceback (most recent call last):
  File "/usr/bin/bitcoinexchangefh", line 9, in <module>
    load_entry_point('BitcoinExchangeFH==0.1.3rc3', 'console_scripts', 'bitcoinexchangefh')()
  File "/usr/lib/python3.4/site-packages/befh/bitcoinexchangefh.py", line 93, in main
    db_client.connect(addr=args.zmqdest)
  File "/usr/lib/python3.4/site-packages/befh/zmq_client.py", line 28, in connect
    self.conn.bind(addr)
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5653)
    # sockopts will still raise just the same, but it will be libzmq doing
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:10014)
    raise ZMQError(errno)
zmq.error.ZMQError: No such device
```
The documentation seems to lack some information on this part.
I hope for some information that shed some light upon this.
Runnung the nodejs client/server combo works without a hitch.
I am not a Pythom programmer, BTW

Thanks!

**Comment by LeonidShamis** [comment]
Could you try replacing "localhost" with "127.0.0.1":

`bitcoinexchangefh -zmq -zmqdest "tcp://127.0.0.1:6001" -instmts subscription.ini`

**Comment by tuxitor** [comment]
This is the output I get:
```
Zmq client is connecting to tcp://127.0.0.1:6001


2017-07-20 03:09:37,204 - INFO 
[[main]]
Subscription file = subscription.ini


2017-07-20 03:09:37,205 - INFO 
[[main]]
Exchange/Instrument/InstrumentCode:
```
Then the program exits without further notice.
This command gives the same result:
```
bitcoinexchangefh -zmq -zmqdest "tcp://127.0.0.1:6001" -csv -csvpath data/ -instmts subscription.ini
```
One question: Is this supposed to act as both a server and client?

In case the program is supposed run in the background, I checked with netstat:
```
netstat -na | grep 'LISTEN ' 
```
gives no sign of port 6001

Thank you!

**Comment by gavincyi** [comment]
Thanks for your input @tuxitor and @LeonidShamis.

Yes I think the documentation states incorrectly on the zmq-tcp destination for localhost. "localhost", instead of "127.0.0.1", never works as the documentation specifies

> An interface may be specified by either of the following:
> 
>     The wild-card *, meaning all available interfaces.
>     The primary IPv4 address assigned to the interface, in its numeric representation.
>     The interface name as defined by the operating system.

For the second question, could you run it again with the following command (subscriptions.ini instead of subscription.ini)

```
bitcoinexchangefh -zmq -zmqdest "tcp://127.0.0.1:6001" -csv -csvpath data/ -instmts subscriptions.ini
```

I think the output message is opaque to tell the subscription file path is invalid. I will resolve it in the next release.

In your case, the application acts as a server at port 6001.

**Comment by tuxitor** [comment]
After nearly giving up when going to bed 3:30 AM, I was not sure I would continue next morning. 
It was a relief get the message next morning and see it working! Stupid typo, even late night.
One change I would like to see though, is to get the timestamp in milliseconds since epoch. What about a configurable format? I would also like to see more options for db and messaging (deepstream, redis, ...)

Thanks a lot!

**Comment by gavincyi** [comment]
Thanks for your suggestion.

The timestamp format has been tracked under #64. 

Meanwhile, I am also looking for more ideas on which db/messaging system users are actively working/using. Open for further ideas. :)
