### ISSUE TITLE
When is a record captured?

### ISSUE THREAD

**Issue by SpaceMonkeyForever** [Aurora-Team/BitcoinExchangeFH#65]
Every row has a trade price and a 5-level order book. Is this simply a record of every trade and the order book at that time? Does that mean it doesn't create a new record every time the order book (most importantly, the top bid/ask) changes but waits for a trade to happen first?

Thank you, I think it's a good idea to add that in the readme file. Thanks for your work tho, I think this is a really good project with a simple 5 minutes setup.

**Comment by SpaceMonkeyForever** [comment]
Looking at the data gain, it looks like it does capture both when a new trade occurs and when the order book updates. That's indicated in the column "update_type", 1 for OB and 2 for trade.

**Comment by gavincyi** [comment]
Yes you're correct. 

For websocket ones, the update depends on the upcoming messages from the exchange. 

For REST ones, the update is returned by the regular requests to the exchange. Most of the exchanges is requested per 500 milliseconds. The request rate sometimes depends on the exchange API usage limit.

Again, thanks for adding more colors into the README file. :)
