### ISSUE TITLE
error: no instrument is found in the subscription file

### ISSUE THREAD

**Issue by aReaSa** [Aurora-Team/BitcoinExchangeFH#76]
hello dear coders thank you for this project but i couldnt run it 

i have an error like this

error: no instrument is found in the subscription file
![ekran alintisi](https://user-images.githubusercontent.com/26048237/29995762-9c9fb5d2-8ff9-11e7-9a53-d53a134e2fd3.PNG)

**Comment by gavincyi** [comment]
Please refer and create the instrument subscription file [subscription.ini](https://github.com/Aurora-Team/BitcoinExchangeFH#Subscription).
