### ISSUE TITLE
ZeroMQ protobuf data model - Type is not expected, and no contract can be inferred

### ISSUE THREAD

**Issue by techguy718** [Aurora-Team/BitcoinExchangeFH#84]
Hi, I'm trying to use this lib with streaming the data via zeromq. I'm new to protobuf so I'm not sure if I'm doing the right thing here:

I have a .proto file like so:

```

syntax = "proto3";

package bfnecn;

message BfnMessage
{
    uint64 trade_px = 1;
    uint64 trade_volume = 2;

    uint64 b1 = 3;
    uint64 b2 = 4;
    uint64 b3 = 5;
    uint64 b4 = 6;
    uint64 b5 = 7;

    uint64 a1 = 8;
    uint64 a2 = 9;
    uint64 a3 = 10;
    uint64 a4 = 11;
    uint64 a5 = 12;

    uint64 bq1 = 13;
    uint64 bq2 = 14;
    uint64 bq3 = 15;
    uint64 bq4 = 16;
    uint64 bq5 = 17;

    uint64 aq1 = 18;
    uint64 aq2 = 19;
    uint64 aq3 = 20;
    uint64 aq4 = 21;
    uint64 aq5 = 22;

    uint32 update_type = 23;
    uint64 order_date_time = 24;
    uint64 trade_date_time = 25;
}

```
I used `protoc` to generate the .cs file on a macbook.

The code that throws an exception is here:

```
var data = socket.Recv();
BfnMessage bfnMessage = ProtobufEx.Deserialize<BfnMessage>(data); 

```

> Exception: System.InvalidOperationException has been thrown
> Type is not expected, and no contract can be inferred: Bfnecn.BfnMessage

I'm not sure if my protofile is right, but how can I get the data out?

**Comment by gavincyi** [comment]
The data is streamed via ZeroMQ's [Publish/Receive](http://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/patterns/pubsub.html) channel. The link is referring to the python usage but I believe there is a wrapper on your language.
