### ISSUE TITLE
Trouble with Poloniex

### ISSUE THREAD

**Issue by micahscopes** [Aurora-Team/BitcoinExchangeFH#85]
I'm having trouble with the Poloniex adapter.  It's just not working.  I get ~80 entries in the sql database, then it just stops updating altogether.

I actually tried some other adapters and didn't have any luck with those either.

It's weird, I'd been collecting lots of data for a few months, then suddenly I started having trouble.  I've tried different versions and can't get anything to work.

Also, I'm not sure what a good debug workflow is for this tool.  Got any suggestions?

**Comment by gavincyi** [comment]
1. Could you provide me the subscription.ini file or the list of your subscription?
2. Is it working for other exchange gateways, e.g. BitMEX/Bitfinex?
3. Which version are you using?

As the exchange gateways can be run as a module library, could you create the following script and share me the output?

```
from befh.exch_poloniex import ExchGwApiPoloniex
from befh.instrument import Instrument
import time
instmt = Instrument(instmt_name="BTC_LTC", instmt_code="BTC_LTC", exchange_name="Poloniex")
for i in range(0, 100):
    print("===============================================")
    print("Time {0}:".format(i))
    print("===============================================")
    order_book = ExchGwApiPoloniex.get_order_book(instmt)
    print("\n".join(["{0} ({1})".format(e.price, e.volume) for e in order_book.bids]))
    time.sleep(1)
```

The script will take roughly two minutes to price the bid order book in every second.

**Comment by micahscopes** [comment]
1.  In order to debug, I've reduced my `instruments.ini` to the following:
```
[Poloniex-USDT-BTC]              
exchange = Poloniex              
instmt_name = usdtbtc            
instmt_code = USDT_BTC           
enabled = 1         
```

2. I think it might be working now for other exchanges.  Bittrex seems to be working alright.  Earlier I needed to restart my computer after an upgrade.

3. I'm using the master branch at the moment.

So the first few times I ran that script, it hung after a few iterations and never recovered.  I did finally managed to get it to run all the way through once.

I don't think I'm being throttled, because if I stop the hung script and start it over again, it immediately gets results.  I'm wondering if maybe Poloniex just leaves requests hanging sometimes.

At this point there is only one row being added when I start bitcoinexchangefh.  Its `id` column gets incremented up to 84 or so, then nothing happens for a long, long time.

**Comment by micahscopes** [comment]
FYI, I was hacking on a fork that *seemed* to work, but I think it wasn't accurately merging new order data into the database;  

I made this fork a while ago, but one thing I do remember discovering was that the timestamps.  I think they weren't in the right timezone, and were set for the future, so Poloniex was always returning empty updates.

But there are more problems that I don't quite understand.

Here's my fork: https://github.com/micahscopes/BitcoinExchangeFH

**Comment by micahscopes** [comment]
Alright, my fork is working now!  I think I understand how the id increment stuff works...
Here were the issues:
1. a unix timestamp from the future meant Poloniex gave back empty results
2. HTTP request timeouts were hanging the threads.  I added a timeout attribute to the requests in `restful_api_socket.py`

Now I'm getting nice, quick results from Poloniex!

**Comment by gavincyi** [comment]
Thanks for spotting out the timeout issue. The fix of timeout issue will be released soon. I did not expect it created such a big impact.

I checked from your forked project and found you get the unix timestamp by the idea of
```
calendar.timegm(...datetime.utctimetuple())
```

Just curious - what is your rationale behind?

**Comment by micahscopes** [comment]
Well, I don't really understand that mess...  I was digging through stackexchange answers about "naive datetimes" and all kinds of funny, unique, special ways to get a GMT timestamp.  It seems like it should be a simple thing to do, but I guess it's not so obvious in Python.  That seemed like the most "simple" way.  Maybe you can make some sense of this: https://stackoverflow.com/questions/5067218/get-utc-timestamp-in-python-with-datetime

**Comment by micahscopes** [comment]
I think Poloniex is getting strict with their throttling.  I'm doing like 1 request/sec and I still get throttled.  I just wish they'd return an error message about it. I think I'm gonna increase my timeout to 5 seconds 🐌

**Comment by gavincyi** [comment]
True. Agree that they are restrictive on the rate limit.
