### ISSUE TITLE
New Exchange Subscriptions Examples

### ISSUE THREAD

**Issue by cryptofiend666** [Aurora-Team/BitcoinExchangeFH#89]
Hi there

Maybe I'm a little daft, but I'm having trouble with Cryptopia and Binance is my subscriptions.ini file.

Is it possible for you to post some examples for these? 

Thanks!

**Comment by gavincyi** [comment]
Instrument name is always application used (can be arbitrary value if you like) while instrument code is exchanged defined (e.g. DOT_BTC in Cryptopia). The exchange name are "Cryptopia" and "Binance" respectively. Please tell if you need further help.
