### ISSUE TITLE
 price depth update (type 1) inconsistent with trade update (type 2)

### ISSUE THREAD

**Issue by igor3210** [Aurora-Team/BitcoinExchangeFH#94]
Hi,

I am using the approch "bitcoinexchangefh -csv -csvpath data/ -instmts subscription.ini" to generate a csv file with price and trade updates for the exchange Kraken. A file is attached for reference.

> 

id | trade_px | trade_volume | b1 | b2 | b3 | b4 | b5 | a1 | a2 | a3 | a4 | a5 | bq1 | bq2 | bq3 | bq4 | bq5 | aq1 | aq2 | aq3 | aq4 | aq5 | order_date_time | trades_date_time | update_type
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1351200 | 7709.1 | 0.003 | 7712 | 7702 | 7700.1 | 7700 | 7699.6 | 7714.9 | 7720 | 7721.8 | 7725 | 7732.1 | 0.003 | 0.09 | 10.741 | 10.652 | 0.006 | 9.853 | 3.727 | 1.291 | 0.08 | 0.002 | 20171116 19:45:47.904587 | 20171116 19:45:34.571597 | 1
1351202 | 7712 | 0.0028527 | 7712 | 7702 | 7700.1 | 7700 | 7699.6 | 7714.9 | 7720 | 7721.8 | 7725 | 7732.1 | 0.003 | 0.09 | 10.741 | 10.652 | 0.006 | 9.853 | 3.727 | 1.291 | 0.08 | 0.002 | 20171116 19:45:47.904587 | 20171116 19:45:52.648815 | 2
1351203 | 7702 | 0.09 | 7712 | 7702 | 7700.1 | 7700 | 7699.6 | 7714.9 | 7720 | 7721.8 | 7725 | 7732.1 | 0.003 | 0.09 | 10.741 | 10.652 | 0.006 | 9.853 | 3.727 | 1.291 | 0.08 | 0.002 | 20171116 19:45:47.904587 | 20171116 19:45:52.656434 | 2
1351204 | 7700.1 | 0.50117012 | 7712 | 7702 | 7700.1 | 7700 | 7699.6 | 7714.9 | 7720 | 7721.8 | 7725 | 7732.1 | 0.003 | 0.09 | 10.741 | 10.652 | 0.006 | 9.853 | 3.727 | 1.291 | 0.08 | 0.002 | 20171116 19:45:47.904587 | 20171116 19:45:52.656936 | 2
1351209 | 7700.1 | 0.50117012 | 7712 | 7700.1 | 7700 | 7699.6 | 7699 | 7714.9 | 7720 | 7721.8 | 7725 | 7732.1 | 0.003 | 10.239 | 10.318 | 0.006 | 0.78 | 9.853 | 3.727 | 1.291 | 0.08 | 0.002 | 20171116 19:45:54.074051 | 20171116 19:45:52.656936 | 1
1351211 | 7700.1 | 0.50117012 | 7712 | 7700.1 | 7700 | 7699.6 | 7699 | 7714.9 | 7720 | 7721.8 | 7725 | 7732.1 | 0.003 | 9.601 | 10.318 | 0.006 | 0.78 | 9.853 | 3.727 | 1.291 | 0.08 | 0.002 | 20171116 19:45:58.994975 | 20171116 19:45:52.656936 | 1
1351218 | 7700.1 | 0.50117012 | 7712 | 7701 | 7700.1 | 7700 | 7699.6 | 7714.7 | 7714.9 | 7716.2 | 7720 | 7721.8 | 0.003 | 0.068 | 9.601 | 10.318 | 0.006 | 0.29 | 9.853 | 1.6 | 3.727 | 1.291 | 20171116 19:46:02.884108 | 20171116 19:45:52.656936 | 1
1351220 | 7700.1 | 0.50117012 | 7712 | 7702.2 | 7701 | 7700.1 | 7700 | 7714.7 | 7714.9 | 7716.2 | 7720 | 7721.8 | 0.003 | 0.003 | 0.068 | 9.601 | 10.318 | 0.29 | 9.853 | 1.6 | 3.727 | 1.291 | 20171116 19:46:06.010960 | 20171116 19:45:52.656936 | 1
1351223 | 7700.1 | 0.50117012 | 7712 | 7702.2 | 7701 | 7700.3 | 7700.1 | 7714.9 | 7720 | 7721.8 | 7725 | 7732.1 | 0.003 | 0.003 | 0.068 | 0.172 | 9.935 | 9.853 | 3.727 | 1.291 | 0.08 | 0.002 | 20171116 19:46:11.368633 | 20171116 19:45:52.656936 | 1
1351227 | 7700.1 | 0.50117012 | 7700.1 | 7700 | 7699.6 | 7699 | 7690 | 7714.9 | 7720 | 7721.8 | 7725 | 7732.1 | 9.815 | 10.318 | 0.006 | 0.78 | 0.323 | 9.853 | 3.727 | 1.291 | 0.08 | 0.002 | 20171116 19:46:16.270117 | 20171116 19:45:52.656936 | 1

**Issue 1**
The index "id" (first column) is not always increasing by 1 unit, e.g. we go from 1351204 to 1351209, does this mean that 5 updates have been lost?

**Issue 2**
Index 1351202 to 1351204 represents 3 trades happening at timestamp 19:45:52.65 for a total volume of 0.0028527+0.09+0.50117012=0.59402282 BTC, however, the subsequent price depth updates do not reflect the any change in volume, note that the first price update following the 3 trades appears almost 2 second after the trades (19:45:54.074051), so it is very strange that the trades did not have any effect on the first level ask or bid volumes.

**Issue 3**
Referring to the same 3 trades mentioned above, the first execution prices is at 7712, which is the current bid price, this looks ok. The second trade (id 1351203) is executed at price 7702, which corresponds to the second best bid (b2), and the third trade is executed as 7700.1 which is the third best bid (b3). So it looks like this was a big sell order which consumed the volumes for the first 3 bid levels. The issue is that there is **no impact on volumes in the order book". Are trade updates and price updates synchronized properly? I noticed this inconsistencies also in other exchanges and there are very frequent.

It looks like the recorded trades and price updates are not reliable.

Attachment
[exch_kraken_xbtusd_snapshot_20171116.txt](https://github.com/Aurora-Team/BitcoinExchangeFH/files/1480150/exch_kraken_xbtusd_snapshot_20171116.txt)

**Comment by gavincyi** [comment]
Issue 1: Are you recording with other instruments as well? The index is across all tables.

Issue 2: Yes there is always latency between order book and trade updates. It is expected.

Issue 3: The order book and trades are directly from the raw result from the exchange queries. It looks to me it requires the exchange to address the latency of such discrepancy.
