### ISSUE TITLE
example ReadMe is incorrect.

### ISSUE THREAD

**Issue by chrischris292** [Aurora-Team/BitcoinExchangeFH#95]
should be subscriptions.ini not subscription.ini for 
`bitcoinexchangefh -sqlite -sqlitepath bitcoinexchangefh.sqlite -instmts subscription.ini`

**Comment by gavincyi** [comment]
Yes thanks for pointing it out.

**Comment by hookerg123** [comment]
I don't believe this has been updated yet?
