### ISSUE TITLE
Order Book Data

### ISSUE THREAD

**Issue by akaniklaus** [Aurora-Team/BitcoinExchangeFH#96]
Hello!

As there is no database of order book movements (in conjunction with order history) for crypto currencies, as opposed to some traditional markets such as NYSE, I would like to urge owners of this repository to extend their work with it. With the recent advancement in Deep Reinforcement Learning, I strongly believe that this data would be valuable for lots of future research in this field. 

Thank you very much for your consideration.

Sincerely,
Kamer

**Comment by gavincyi** [comment]
Thanks a lot for your suggestion. I have been shifting my current focus to another project "[libcryptomarket](https://github.com/libcryptomarket/libcryptomarket)", which targets on the researchers's need. I'm happy if you raise your requirements over there. I believe it can facilitate researchers' work on cryptocurrency market.
