### ISSUE TITLE
The problem to install on Ubuntu 16.04

### ISSUE THREAD

**Issue by ValmonZ** [Aurora-Team/BitcoinExchangeFH#99]
I can`t install bitcoinexchangefh on Ubuntu 16.04 with python 3.6
I have such a mistake: failed install qpython (because qpython only for pyrhon 2.7). When I did it on Windows i installed visual studio and the problem took away. 
Have you any ideas to resolve this problem?
![screenshot from 2017](https://user-images.githubusercontent.com/34619458/34078141-488065da-e325-11e7-903b-a1448456e21e.jpg)

**Comment by gavincyi** [comment]
Please install `sudo apt-get install build-essential` in your ubuntu platform if you find `gcc --version` returns the similar error. It looks to me the gcc is not installed yet.
